#!/bin/bash

# Install clojure to ~/.local
# So it can be installed without sudo
curl -O https://download.clojure.org/install/linux-install-1.10.1.754.sh
chmod +x linux-install-1.10.1.754.sh
./linux-install-1.10.1.754.sh --prefix ${HOME}/.local
rm -rf linux-install-1.10.1.754.sh

# Install clojupyter with deps.edn
make install